# Case Study on Numpy and Pandas

In [72]:
import numpy as np
import pandas as pd

df=pd.read_csv("auto-mpg.csv")
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

# NumPy

##1. **Basic Array Operations**

Convert the mpg column into a NumPy array and calculate:
* The mean, median, and standard deviation of mpg.
* The number of cars with mpg greater than 25.


In [73]:
mpg_np= np.asarray(df.mpg)

print("                            Mean value of mpg = ",np.mean(mpg_np))
print("                          Median value of mpg = ",np.median(mpg_np))
print("              Standard Deviation value of mpg = ",np.std(mpg_np))

print("      Number of cars with mpg greater than 25 = ",np.sum(mpg_np > 25))




                            Mean value of mpg =  23.514572864321607
                          Median value of mpg =  23.0
              Standard Deviation value of mpg =  7.806159061274433
      Number of cars with mpg greater than 25 =  158


##2. **Filtering**

Using NumPy, filter all cars with more than 6 cylinders.
Return the corresponding car_name as a list.

In [74]:
cyl_np = np.asarray(df.cylinders)
car_np=np.asarray(df["car name"])
car_name=[]

for i in range(cyl_np.size):
  if cyl_np[i]>6:
    car_name.append(car_np[i])

car_name

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

##3. **Statistical Analysis**

Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [75]:
weight_np=np.asarray(df.weight)

print(" Quartile 1 (25th percentile) = ", np.percentile(weight_np,25))
print(" Quartile 2 (50th percentile) = ", np.percentile(weight_np,50))
print(" Quartile 3 (75th percentile) = ", np.percentile(weight_np,75))

print( '\n'" Verifying using median= ",np.median(weight_np))

 Quartile 1 (25th percentile) =  2223.75
 Quartile 2 (50th percentile) =  2803.5
 Quartile 3 (75th percentile) =  3608.0

 Verifying using median=  2803.5


##4. **Array Manipulation**

Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [76]:
acc_np=np.asarray(df.acceleration)
print("INITIAL ARRAY" )
print(acc_np)

max_acc=acc_np.max(axis=0)
min_acc=acc_np.min(axis=0)

print('\n'"MAXIMUM & MINIMUM VALUES")
print(max_acc)
print(min_acc)

acc_np=((acc_np-min_acc)/(max_acc-min_acc))

print('\n'"NORMALIZED ARRAY ( BETWEEN 0 and 1)")
print(acc_np)


INITIAL ARRAY
[12.  11.5 11.  12.  10.5 10.   9.   8.5 10.   8.5 10.   8.   9.5 10.
 15.  15.5 15.5 16.  14.5 20.5 17.5 14.5 17.5 12.5 15.  14.  15.  13.5
 18.5 14.5 15.5 14.  19.  13.  15.5 15.5 15.5 15.5 12.  11.5 13.5 13.
 11.5 12.  12.  13.5 19.  15.  14.5 14.  14.  19.5 14.5 19.  18.  19.
 20.5 15.5 17.  23.5 19.5 16.5 12.  12.  13.5 13.  11.5 11.  13.5 13.5
 12.5 13.5 12.5 14.  16.  14.  14.5 18.  19.5 18.  16.  17.  14.5 15.
 16.5 13.  11.5 13.  14.5 12.5 11.5 12.  13.  14.5 11.  11.  11.  16.5
 18.  16.  16.5 16.  21.  14.  12.5 13.  12.5 15.  19.  19.5 16.5 13.5
 18.5 14.  15.5 13.   9.5 19.5 15.5 14.  15.5 11.  14.  13.5 11.  16.5
 17.  16.  17.  19.  16.5 21.  17.  17.  18.  16.5 14.  14.5 13.5 16.
 15.5 16.5 15.5 14.5 16.5 19.  14.5 15.5 14.  15.  15.5 16.  16.  16.
 21.  19.5 11.5 14.  14.5 13.5 21.  18.5 19.  19.  15.  13.5 12.  16.
 17.  16.  18.5 13.5 16.5 17.  14.5 14.  17.  15.  17.  14.5 13.5 17.5
 15.5 16.9 14.9 17.7 15.3 13.  13.  13.9 12.8 15.4 14.5 17.6 17.6 22.2

##5. **Broadcasting**

Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.


In [77]:

print("Initial values in the data")
print( np.array(df.horsepower))


df.horsepower = pd.to_numeric(df.horsepower, errors = 'coerce')   # converts the non numeric values to 'nan'
print("changed all to numeric")
print( np.array(df.horsepower))

mean_hp=df.horsepower.mean()

print('\n' " the MEAN value is =", mean_hp)
print('\n' "changed nan to mean")
df.horsepower = df.horsepower.fillna(mean_hp)          # replaces 'nan' values with the mean value.
print( np.array(df.horsepower))

hp_np = np.asarray((df.horsepower)*(1.1))                # increasing the value by 10%

print("**************************************" )
print( "Increase all horsepower values by 10% ")
print(hp_np)
print("**************************************" )
#hp_np= np.to_numeric (hp_np)
#print(hp_np)



Initial values in the data
['130' '165' '150' '150' '140' '198' '220' '215' '225' '190' '170' '160'
 '150' '225' '95' '95' '97' '85' '88' '46' '87' '90' '95' '113' '90' '215'
 '200' '210' '193' '88' '90' '95' '?' '100' '105' '100' '88' '100' '165'
 '175' '153' '150' '180' '170' '175' '110' '72' '100' '88' '86' '90' '70'
 '76' '65' '69' '60' '70' '95' '80' '54' '90' '86' '165' '175' '150' '153'
 '150' '208' '155' '160' '190' '97' '150' '130' '140' '150' '112' '76'
 '87' '69' '86' '92' '97' '80' '88' '175' '150' '145' '137' '150' '198'
 '150' '158' '150' '215' '225' '175' '105' '100' '100' '88' '95' '46'
 '150' '167' '170' '180' '100' '88' '72' '94' '90' '85' '107' '90' '145'
 '230' '49' '75' '91' '112' '150' '110' '122' '180' '95' '?' '100' '100'
 '67' '80' '65' '75' '100' '110' '105' '140' '150' '150' '140' '150' '83'
 '67' '78' '52' '61' '75' '75' '75' '97' '93' '67' '95' '105' '72' '72'
 '170' '145' '150' '148' '110' '105' '110' '95' '110' '110' '129' '75'
 '83' '100' '78' '96' '71' 

##6. **Boolean Indexing**

Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing

In [78]:

origin_np = np.asarray(df.origin)
disp_np = np.asarray(df.displacement)
valid_arr=[]

for i in range(origin_np.size):
  if origin_np[i]==2:
    valid_arr.append(disp_np[i])

print(" The average displacement of cars with an origin of 2 Europe = ",np.mean(valid_arr))

 The average displacement of cars with an origin of 2 Europe =  109.14285714285714


##7. **Matrix Operations**

Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [79]:
matrix_1 = np.asarray([(df.mpg), (df.horsepower), (df.weight)])    # not the answer to this question but, informative
print(matrix_1)

# they have non numeric values
df.mpg = pd.to_numeric(df.mpg, errors = 'coerce')
df.horsepower = pd.to_numeric(df.horsepower, errors = 'coerce')
df.weight = pd.to_numeric(df.weight, errors = 'coerce')

# replacing nan vlues with mean of each column
df.mpg = df.mpg.fillna(df.mpg.mean())
df.horsepower = df.horsepower.fillna(df.horsepower.mean())
df.weight = df.weight.fillna(df.weight.mean())

matrix_np = matrix_1.transpose()          # method 1 to get the matrix in this format
print(matrix_np)
print((matrix_np).dtype)

matrix_np = np.asarray(df[['mpg', 'horsepower', 'weight']])   # method 2 to get the matrix in this format

# can be used to convert the type of data in the matrix. need to make sure all are numeric before doing this operation
matrix_np_float = np.float64(matrix_np)
print((matrix_np).dtype)
print(matrix_np)

given_vector= [1,0.5,-0.2] # by default, it will be a column vector. so, no need to take transpose to find the dot product.
dot_prod = np.dot(matrix_np,given_vector)

print(" dot product of the vectors will be ")

print(dot_prod)


[[  18.   15.   18. ...   32.   28.   31.]
 [ 130.  165.  150. ...   84.   79.   82.]
 [3504. 3693. 3436. ... 2295. 2625. 2720.]]
[[  18.  130. 3504.]
 [  15.  165. 3693.]
 [  18.  150. 3436.]
 ...
 [  32.   84. 2295.]
 [  28.   79. 2625.]
 [  31.   82. 2720.]]
float64
float64
[[  18.  130. 3504.]
 [  15.  165. 3693.]
 [  18.  150. 3436.]
 ...
 [  32.   84. 2295.]
 [  28.   79. 2625.]
 [  31.   82. 2720.]]
 dot product of the vectors will be 
[-617.8        -641.1        -594.2        -595.6        -602.8
 -754.2        -746.8        -740.9        -758.5        -660.
 -612.6        -627.8        -662.2        -490.7        -402.9
 -497.1        -488.3        -453.9        -355.         -318.
 -465.9        -417.         -402.5        -364.3        -463.6
 -805.5        -765.2        -760.4        -840.9        -355.
 -379.8        -373.1        -331.96530612 -457.8        -619.3
 -598.8        -597.4        -589.6        -745.3        -791.3
 -740.3        -730.2        -889.         -

##8. **Sorting**

Use NumPy to sort the cars by model_year in descending order and display the first
five car names.

In [80]:
model_car_np = np.array(df[['model year', 'car name']])
#sorting based on first column
sorted_cars = model_car_np[np.argsort(model_car_np[:, 0])[::-1]]    # model_car_np[:, 0]) = sort by 0th column.   [::-1] descending
#print(model_car_np)  # initial list
#print(sorted_cars)   # sorted list - descending
print(sorted_cars[:5, :]) # first 5 data from sorted list

[[82 'chevy s-10']
 [82 'honda accord']
 [82 'ford ranger']
 [82 'chevrolet cavalier']
 [82 'chevrolet cavalier wagon']]


##9. **Correlation**

Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [81]:
mpg_np = np.array(df.mpg)
wight_np= np.array(df.weight)

pearson_coeff= np.corrcoef(mpg_np,wight_np)

print(pearson_coeff)

[[ 1.         -0.83174093]
 [-0.83174093  1.        ]]


##10. **Conditional Aggregates**

Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [82]:
mpg_np = np.array(df.mpg)
cyl_np = np.asarray(df.cylinders)

distinct_cyl=np.unique(cyl_np)
mean_mpg_for_cyl_group = {cyl: mpg_np[cyl_np == cyl].mean() for cyl in distinct_cyl}
print(mean_mpg_for_cyl_group)

{3: 20.55, 4: 29.28676470588235, 5: 27.366666666666664, 6: 19.985714285714284, 8: 14.963106796116506}


# Pandas


##1. **Basic Exploration**

Load the dataset into a Pandas DataFrame. Display:

* The first 10 rows
* The total number of rows and columns
* Summary statistics for numerical columns

In [83]:
df=pd.read_csv("auto-mpg.csv")
print("************************************")
print("The first 10 rows")
print(df.head(10))
print("************************************")
print('\n')

print("************************************")
rows, columns = df.shape
print(f"Rows: {rows}, Columns: {columns}")
print("************************************")
print('\n')

print("******************************************")
print("Summary statistics for numerical columns")
print('\n')
print(df.describe())
print("******************************************")



************************************
The first 10 rows
    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  che

##2. **Filtering and Indexing**

Find all cars manufactured in 1975 with a weight less than 3000. Return the
DataFrame with selected columns: car_name, weight, and mpg.

In [84]:
df_filtered = df[(df['model year'] == 75) & (df['weight'] < 3000)]
selected_columns = ['car name', 'weight', 'mpg']
print(df_filtered[selected_columns])


              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


##3. **Handling Missing Data**

Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [85]:
print(df.isnull().sum())
print('\n' "Initial horsepower values")
print(np.array(df.horsepower))
# horsepower column has non numeric values
df.horsepower = pd.to_numeric(df.horsepower, errors = 'coerce')
print('\n' "all numeric horsepower values")
print(np.array(df.horsepower))
# replacing nan vlues with median of horsepower column
df.horsepower = df.horsepower.fillna(df.horsepower.median())
print('\n' "nan replaced with median")
print(np.array(df.horsepower))


mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

Initial horsepower values
['130' '165' '150' '150' '140' '198' '220' '215' '225' '190' '170' '160'
 '150' '225' '95' '95' '97' '85' '88' '46' '87' '90' '95' '113' '90' '215'
 '200' '210' '193' '88' '90' '95' '?' '100' '105' '100' '88' '100' '165'
 '175' '153' '150' '180' '170' '175' '110' '72' '100' '88' '86' '90' '70'
 '76' '65' '69' '60' '70' '95' '80' '54' '90' '86' '165' '175' '150' '153'
 '150' '208' '155' '160' '190' '97' '150' '130' '140' '150' '112' '76'
 '87' '69' '86' '92' '97' '80' '88' '175' '150' '145' '137' '150' '198'
 '150' '158' '150' '215' '225' '175' '105' '100' '100' '88' '95' '46'
 '150' '167' '170' '180' '100' '88' '72' '94' '90' '85' '107' '90' '145'
 '230' '49' '75' '91' '112' '150' '110' '122' '180' '95' '?' '100' '100'
 '67' '80' '65' '75' '100' '110' '105' '140' '150' '150' '140' '150' 

##4. **Data Transformation**

Add a new column power_to_weight_ratio, calculated as horsepower / weight.


In [86]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']

df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  
0            70       1  chevrolet chevelle malibu               0.037100  
1            70       1          buick skylark 320               0.044679  
2            70       1         plymouth satellite               0.043655  
3            70       1              amc rebel sst               0.043694  
4            70       1                ford torino               0.040591  
..          ...     ...                        ...                    ...  
393          82       1            ford mustang gl               0.030824  
394          82       2                  vw pickup               0.024413  
395          82       1              dodge rampage               0.036601  
396          82       1                ford ranger               0.030095  
397          82       1                 chevy s-10               0.030147  

[398 rows x 10 columns]

##5. **Group By**

Group the cars by origin and calculate the mean mpg for each group.

In [87]:
df.groupby(['origin'])['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

##6. **Sorting**

Sort the DataFrame by mpg in descending order and display the top 10 cars with
the highest mpg.

In [88]:
df_sort = df.sort_values(by='mpg', ascending=False)
df_sort.head(10)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

##7. **Apply Function**
Apply this function to each row and store the result in the new column.
Create a new column performance_score using a custom function:

def performance_score(row):
  return row['mpg'] * row['acceleration'] / row['weight']

In [89]:
def performance_score(row):
  return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1) [1]
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0              0.04671  
1              0.04671  
2              0.04671  
3              0.04671  
4              0.04671  
..                 ...  
393            0.04671  
394            0.04671  
395            0.04671  
396            0.04671  
397            0.04671  

[398 rows x 11 columns]

##8. **Visualization Preparation**
Generate a summary DataFrame with:

*  Average mpg, weight, and horsepower for each model_year.

In [90]:
df_summary = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()
df_summary

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

##9. **Exporting Data**

Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [91]:
df_high_mpg = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]

df_high_mpg.to_csv('high_mpg_cars.csv', index=False)

##10. **Finding Anomalies**

Identify potential outliers in the mpg column using the Interquartile Range (IQR)
method. Specifically:
● Calculate the IQR for mpg.

● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.

● Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
and model_year.

In [92]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

lower_limit = Q1 - (1.5 * IQR)
upper_limit = Q3 + (1.5 * IQR)

# finding outliers in the mpg
mpg_outliers = df[(df['mpg'] < lower_limit) | (df['mpg'] > upper_limit)]

df_outlier = mpg_outliers[['car name', 'mpg', 'model year']]

df_outlier

car name   mpg  model year
322  mazda glc  46.6          80